### ISSUE TITLE
Add example dyads of SpelledPitch values to demonstrate rule generation

### ISSUE THREAD

**Issue by jsbean** [jsbean/PitchSpelling#2]
Using the given template:
#### Raw:

```
|  Pitch Class A   |  Pitch Class B   | Rule broken |
|------------------|------------------|-------------|
| spelled pitch A1 | spelled pitch B1 | rule broken |
| --               | spelled pitch B2 | ...         |
| --               | spelled pitch B3 | ...         |
| spelled pitch A2 | spelled pitch B1 | ...         |
| --               | spelled pitch B2 | ...         |
| --               | spelled pitch B3 | ...         |
```
#### Markdown result:

| A | B | Rule broken |
| --- | --- | --- |
| spelled pitch A1 | spelled pitch B1 | rule broken |
| -- | spelled pitch B2 | ... |
| -- | spelled pitch B3 | ... |
| spelled pitch A2 | spelled pitch B1 | ... |
| -- | spelled pitch B2 | ... |
| -- | spelled pitch B3 | ... |

**Comment by jsbean** [comment]
Down the line, add a link to the rule broken, as declared in #1.

**Comment by mossheim** [comment]
seems like most of the possible rules have been discovered, now that we have an example case with two eighth-tone-resolution pitch classes. anything you'd like me to try?

**Comment by jsbean** [comment]
What if you did just a couple with a wider interval, and not based on `c`. See if anything strange pops up.

**Comment by mossheim** [comment]
Sure, I could try {3.5, 10.25} (E-quarter-flat, B-quarter-flat-down)

**Comment by jsbean** [comment]
Beautiful.

**Comment by mossheim** [comment]
I added (3.5, 10.25), (2.25, 9) and (2.25, 5.25) to the page. I don't really see any special cases except for one you already talked about, where preference should be given to spellings like (D down, F-q-sharp down) even though the node (F up) has lower cost. I think I'd prefer to wait until we see an implementation in action before making the rule set more complex. You can close this issue if you're satisfied 👍

**Comment by jsbean** [comment]
This is beautiful -- I should've done the 2D table :).
