### ISSUE TITLE
Concisely define the crossover/reacharound rule (Re2).

### ISSUE THREAD

**Issue by mossheim** [jsbean/PitchSpelling#5]

**Comment by jsbean** [comment]
I'll do my best to get a working definition going. Then maybe you can make it concise if I fail to.

**Comment by jsbean** [comment]
I provided the skeleton for a definition, that requires work in either of two directions:
- Package `letterName`, `quarterStep`, and `eighthStep` into a single structure (as it is done [here](https://github.com/dn-m/PitchSpellingTools/blob/interval-classifier/PitchSpellingTools/PitchSpelling.swift)), or
- Make the definition considerably more verbose

**Comment by mossheim** [comment]
I think packaging those things together makes sense. The definition you wrote does make rough sense, but the issue with a simple < comparison is that it doesn't account for modulo wrapping. I'm going to try on my own now and I'll share what I come up with.

**Comment by jsbean** [comment]
Ahh right, please do.

**Comment by mossheim** [comment]
Check out the new definition. What do you think? It takes  more calculation than other rules but I think that's OK.

**Comment by jsbean** [comment]
I think that's quite alright! Closing.
