### ISSUE TITLE
How specifically do we define an augmented interval?

### ISSUE THREAD

**Issue by mossheim** [jsbean/PitchSpelling#7]
Especially in the case of quarter tone spellings.

For example, is (C, A-three-quarter-flat up) a diminished 6th?

**Comment by mossheim** [comment]
Another example - is (C up, F-quarter-sharp up) augmented?

Do we add an understanding of quarter-step resolution to augmented intervals? Or is it just half-step scaled? I would prefer that since I think it would simplify a lot of logic, and in this case I think both intervals I've named would be non-aug/dim.

**Comment by mossheim** [comment]
However, this would mean that (C, D# down) would be counted as a major second, which I'm not sure I'm okay with. hmmm...

edit: I can't think of any simple way to resolve this other than by making the aug/dim test scale to the finest (8th-tone) resolution. That way (C, Eb-down) would still be preferred, slightly.

**Comment by jsbean** [comment]
This is an excellent question: this is very related to my incoherent ramblings at the Orangerie about extending the `NamedInterval` data structure to have knowledge and names for quarter-step and eighth-step intervals.

My solution up to now has been to quantize quarter-tone resolutions to their half-step counterpart (`.quarterSharp` becomes `.sharp` and `.quarterFlat` becomes `.flat`, for the purpose of defining its interval quality). Of course, I haven't been dealing with triple sharps, let alone triple-and-a-half sharps.

At this point, the eighth-step modifier is not considered, as the rules that would render them valid or invalid in the context of pitch spelling, would be taken care of an eighth-step-specific rule.

I do think it would be worthwhile to investigate the generation of a systematic lexicon for these microtonal intervals (similar to `neutral second`, `neutral third`), extending up to eighth-step relationships (with affordances for defining, e.g., a perfect fifth but expanded twice with a lower down-arrow and an upper up-arrow).

For now, I'd say keep with the quantization.

**Comment by mossheim** [comment]
Right, I understand now why you said that!

Just so we're clear, you're doing that `q-sharp -> sharp` and `q-flat -> flat` quantization before determining interval size? Wouldn't that mean that `(D q-flat, F q-sharp)`, a major third, would be recognized by your method as an augmented third?

I guess I think it makes more sense not to quantize, although maybe the penalty can be applied in a quantized way. But I think I need to hear more about where/when you're planning to use this first, because that's still a mystery to me.

I'm going to open an issue for the interval naming lexicon.

**Comment by jsbean** [comment]
`(d, .quarterFlat), (f, .quarterSharp)` is an excellent example of why we should extend the knowledge.

In fact, to the extent that I was using these structures, it wasn't critical what the named interval of such an interval would be, because the `sharp/flat` rule would be broken and ruled out immediately anyway.

But it should be critical. Open away!

**Comment by mossheim** [comment]
Ahh, I see. That's a good point. I think a lot of the rules cover common ground--it will be interesting once we have the basic thing up and running to see if we can eliminate rules and still get good results!

**Comment by jsbean** [comment]
You are super-right: check #9.

**Comment by jsbean** [comment]
Closing this as I think we are zoning into a solution with #8.
