### ISSUE TITLE
Remove reacharound, unisons rules

### ISSUE THREAD

**Issue by jsbean** [jsbean/PitchSpelling#9]
The following rules are special cases of rule [**R<sub>e3</sub>: Augmented / diminished intervals**](https://github.com/jsbean/PitchSpelling/blob/master/PitchSetSpellingRules.md#re3-augmented--diminished-intervals) rule.:
- [**R<sub>e2</sub>: Crossovers**](https://github.com/jsbean/PitchSpelling/blob/master/PitchSetSpellingRules.md#re2-crossovers) aka "reacharounds"
- [**R<sub>e1</sub>: Unisons**](https://github.com/jsbean/PitchSpelling/blob/master/PitchSetSpellingRules.md#re1-unisons) 

Remove them for logical orthogonality.

This is a good place to test the `Pull Request` mechanism.
- [ ] Create a branch called something like: `refine-pitchsetspellingrules`
- [ ] Make the edits to `PitchSetSpellingRules.md`
- [ ] Open a `Pull Request`
- [ ] We merge it
- [ ] See how that feels

**Comment by jsbean** [comment]
@brianlheim, how does this feel in terms of your implementation?

**Comment by mossheim** [comment]
I think that the crossover and unison rules are actually still very useful in applying an additional penalty to already-bad spellings. For now I think we should keep them, because they do make large trees much easier to explore and they don't add that much cost for small trees.

**Comment by jsbean** [comment]
K! So this dimension of n-jeopardy is a good one. Closing for now.
